services:
  whisperr-videos:
    build: .
    runtime: nvidia
    volumes:
      - ./models:/root/.cache/whisper
      - ./audio-files:/app/audio-files
      - ./output:/app/output
    env_file:
      - .env
    command: /app/process_audio.sh
